const itemsWedding = [
{
    id: 8001,
    ureticiAdi: 'XYZ Firma',
    gelinlikAdi: 'Düğün Salonu',
    fiyat: '7.000 - 9.000',
    imageUrl: 'image-url',
    firma: 'XYZ Firma',
    il: 'İstanbul',
    etekKesimi: 'A Kesimi',
    yakaTipi: 'V Yaka',
    tarzOzellik: 'Vintage',
    kumasAksesuar: 'Dantel, Tül',
    dekolteTipi: 'Göğüs Dekolteli',
    etekBoyu: 'Uzun Boy',
    kolTipi: 'Kolsuz',
    renk: 'Beyaz',
    kiralamaOpsiyonu: 'Kiralanamaz',
    tur: 'Gelinlik',
    aciklama: [
        'Belden itibaren A harfi çizerek inen A kesim gelinlikler, her vücut tipi için ideal!',
        'Omuzları öne çıkaran bu straplez yaka gelinlik, özellikle açık ya da yarım toplu saç modelleri ile büyük bir uyum sağlıyor.',
        'Sen de fazla gösterişten hoşlanmıyor ve özellikle aile arasında küçük bir törenle evlenmeyi planlıyorsan, bu sade tarzdaki gelinliği düşünebilirsin!',
        'Pürüzsüz ve sert yapıya sahip mikado kumaştan hazırlanan bu gelinlik, sonbahar ve kış aylarında evlenecek gelinlerin favorisi olacak.'
    ],
    thumbnails: [
        "https://dugunrehberi.com.tr/img/firmalar/b/h_1486812255_4.jpg",
        "https://i.dugun.com/gallery/56867/preview_subasi-dugun-salonu_AEnhH0PR.jpg",
        "https://nefesorman.com/wp-content/uploads/2024/02/istanbul-kir-dugun-salonu-nefes-servi-31231.jpg",
        "https://www.kocaeli.bel.tr/files/uploads/services/default/20231123-dugun-salonlari-346941-c024f3cf024bd4446528.jpg",
        "https://static.fead.co/uploads/places/2018-06-10/a4MAaboW56BZHd12.JPG",
        "https://www.acelyadugunsalonu.com/index_htm_files/1520.jpg"
    ],
},
{
    id: 8002,
    ureticiAdi: 'XYZ Firma',
    gelinlikAdi: 'Düğün Salonu',
    fiyat: '7.000 - 9.000',
    imageUrl: 'image-url',
    firma: 'XYZ Firma',
    il: 'İstanbul',
    etekKesimi: 'A Kesimi',
    yakaTipi: 'V Yaka',
    tarzOzellik: 'Vintage',
    kumasAksesuar: 'Dantel, Tül',
    dekolteTipi: 'Göğüs Dekolteli',
    etekBoyu: 'Uzun Boy',
    kolTipi: 'Kolsuz',
    renk: 'Beyaz',
    kiralamaOpsiyonu: 'Kiralanamaz',
    tur: 'Gelinlik',
    aciklama: [
        'Belden itibaren A harfi çizerek inen A kesim gelinlikler, her vücut tipi için ideal!',
        'Omuzları öne çıkaran bu straplez yaka gelinlik, özellikle açık ya da yarım toplu saç modelleri ile büyük bir uyum sağlıyor.',
        'Sen de fazla gösterişten hoşlanmıyor ve özellikle aile arasında küçük bir törenle evlenmeyi planlıyorsan, bu sade tarzdaki gelinliği düşünebilirsin!',
        'Pürüzsüz ve sert yapıya sahip mikado kumaştan hazırlanan bu gelinlik, sonbahar ve kış aylarında evlenecek gelinlerin favorisi olacak.'
    ],
    thumbnails: [
        "https://dugunrehberi.com.tr/img/firmalar/b/h_1486812255_4.jpg",
        "https://i.dugun.com/gallery/56867/preview_subasi-dugun-salonu_AEnhH0PR.jpg",
        "https://nefesorman.com/wp-content/uploads/2024/02/istanbul-kir-dugun-salonu-nefes-servi-31231.jpg",
        "https://www.kocaeli.bel.tr/files/uploads/services/default/20231123-dugun-salonlari-346941-c024f3cf024bd4446528.jpg",
        "https://static.fead.co/uploads/places/2018-06-10/a4MAaboW56BZHd12.JPG",
        "https://www.acelyadugunsalonu.com/index_htm_files/1520.jpg"
    ],
},
{
    id: 8003,
    ureticiAdi: 'XYZ Firma',
    gelinlikAdi: 'Düğün Salonu',
    fiyat: '7.000 - 9.000',
    imageUrl: 'image-url',
    firma: 'XYZ Firma',
    il: 'İstanbul',
    etekKesimi: 'A Kesimi',
    yakaTipi: 'V Yaka',
    tarzOzellik: 'Vintage',
    kumasAksesuar: 'Dantel, Tül',
    dekolteTipi: 'Göğüs Dekolteli',
    etekBoyu: 'Uzun Boy',
    kolTipi: 'Kolsuz',
    renk: 'Beyaz',
    kiralamaOpsiyonu: 'Kiralanamaz',
    tur: 'Gelinlik',
    aciklama: [
        'Belden itibaren A harfi çizerek inen A kesim gelinlikler, her vücut tipi için ideal!',
        'Omuzları öne çıkaran bu straplez yaka gelinlik, özellikle açık ya da yarım toplu saç modelleri ile büyük bir uyum sağlıyor.',
        'Sen de fazla gösterişten hoşlanmıyor ve özellikle aile arasında küçük bir törenle evlenmeyi planlıyorsan, bu sade tarzdaki gelinliği düşünebilirsin!',
        'Pürüzsüz ve sert yapıya sahip mikado kumaştan hazırlanan bu gelinlik, sonbahar ve kış aylarında evlenecek gelinlerin favorisi olacak.'
    ],
    thumbnails: [
        "https://dugunrehberi.com.tr/img/firmalar/b/h_1486812255_4.jpg",
        "https://i.dugun.com/gallery/56867/preview_subasi-dugun-salonu_AEnhH0PR.jpg",
        "https://nefesorman.com/wp-content/uploads/2024/02/istanbul-kir-dugun-salonu-nefes-servi-31231.jpg",
        "https://www.kocaeli.bel.tr/files/uploads/services/default/20231123-dugun-salonlari-346941-c024f3cf024bd4446528.jpg",
        "https://static.fead.co/uploads/places/2018-06-10/a4MAaboW56BZHd12.JPG",
        "https://www.acelyadugunsalonu.com/index_htm_files/1520.jpg"
    ],
},
{
    id: 8004,
    ureticiAdi: 'XYZ Firma',
    gelinlikAdi: 'Düğün Salonu',
    fiyat: '7.000 - 9.000',
    imageUrl: 'image-url',
    firma: 'XYZ Firma',
    il: 'İstanbul',
    etekKesimi: 'A Kesimi',
    yakaTipi: 'V Yaka',
    tarzOzellik: 'Vintage',
    kumasAksesuar: 'Dantel, Tül',
    dekolteTipi: 'Göğüs Dekolteli',
    etekBoyu: 'Uzun Boy',
    kolTipi: 'Kolsuz',
    renk: 'Beyaz',
    kiralamaOpsiyonu: 'Kiralanamaz',
    tur: 'Gelinlik',
    aciklama: [
        'Belden itibaren A harfi çizerek inen A kesim gelinlikler, her vücut tipi için ideal!',
        'Omuzları öne çıkaran bu straplez yaka gelinlik, özellikle açık ya da yarım toplu saç modelleri ile büyük bir uyum sağlıyor.',
        'Sen de fazla gösterişten hoşlanmıyor ve özellikle aile arasında küçük bir törenle evlenmeyi planlıyorsan, bu sade tarzdaki gelinliği düşünebilirsin!',
        'Pürüzsüz ve sert yapıya sahip mikado kumaştan hazırlanan bu gelinlik, sonbahar ve kış aylarında evlenecek gelinlerin favorisi olacak.'
    ],
    thumbnails: [
        "https://dugunrehberi.com.tr/img/firmalar/b/h_1486812255_4.jpg",
        "https://i.dugun.com/gallery/56867/preview_subasi-dugun-salonu_AEnhH0PR.jpg",
        "https://nefesorman.com/wp-content/uploads/2024/02/istanbul-kir-dugun-salonu-nefes-servi-31231.jpg",
        "https://www.kocaeli.bel.tr/files/uploads/services/default/20231123-dugun-salonlari-346941-c024f3cf024bd4446528.jpg",
        "https://static.fead.co/uploads/places/2018-06-10/a4MAaboW56BZHd12.JPG",
        "https://www.acelyadugunsalonu.com/index_htm_files/1520.jpg"
    ],
},
];
export default itemsWedding;